server:
  port: ${PORT:8880}

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  cloud:
    config:
      server:
        git:
          uri: ${URI_PATH:https://github.com/nir3c/configuration.git}
          search-paths: ${SEARCH_PATH:configuration-repository/config}
